"""init

Revision ID: 8f357ecd926b
Revises: 
Create Date: 2024-08-20 14:37:14.772533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f357ecd926b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('original_url', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index(op.f('ix_message_code'), 'message', ['code'], unique=True)
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_unsubscribe', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('acc_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['message.code'], name=op.f('fk_subscribe_code_message'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscribe'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe')
    op.drop_index(op.f('ix_message_code'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
